import Head from 'next/head'
import Counter from '../components/Counter'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-3xl font-bold underline">hola</h1>
      <Counter />
    </div>
  )
}
